spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: andrey
    password: andrey
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          connecttimeout: 5000
          timeout: 3000
          writetimeout: 3000
          starttls:
            enable: true

security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: notification-service-secret
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: internal
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

server:
  port: 8084

logging:
  level:
    ROOT: INFO
