spring:
  application:
    name: task-service

security:
  oauth2:
    client:
      clientId: task-service
      clientSecret: task-service-secret
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: internal
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

server:
  port: 8083

logging:
  level:
    ROOT: DEBUG