spring:
  application:
    name: account-service

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: account-service-secret
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: internal
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

server:
  port: 8082

logging:
  level:
    ROOT: DEBUG