node {
	stage('Checkout') {
		git 'file:///home/andrey/Development/service-registration'
	}
	
	stage('Clean') {
		sh './gradlew clean build -p account-service'
	}
	
	stage('Image') {
		dir ('account-service') {
			sh 'docker build -t asatnin/account-service:latest .'
		}
	}
	
	stage('Run') {
		docker.image("asatnin/account-service").run('-p 8082:8082')
	}
	
	stage ('Final') {
            build job: 'task-service-pipeline', wait: false
        }
}
